server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: SpringPlusTeamProject

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
#    property-naming-strategy: SNAKE_CASE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      use_sql_comments: true
    open-in-view: false

  jwt:
    token:
      access:
        minute: 15
      refresh:
        minute: 20160
    secret: ${SECRET_KEY}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true

cache:
  ttl:
    values:
      friends:
        minutes: 15
